# Generated by Django 4.2.11 on 2024-03-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AssetExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_buying', to='gql.asset')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gql.route')),
                ('selling_asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_selling', to='gql.asset')),
            ],
        ),
    ]
