# Generated by Django 4.2.11 on 2024-03-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='gecko_id',
            field=models.CharField(default='not-set', max_length=64),
            preserve_default=False,
        ),
    ]
