# Generated by Django 4.2.11 on 2024-03-29 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0002_asset_gecko_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gecko_pool_id', models.CharField(max_length=64)),
                ('base_token', models.CharField(max_length=64)),
                ('quote_token', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('network', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gql.pool'),
        ),
    ]
