# Generated by Django 4.2.11 on 2024-03-29 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0003_pool_route_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='pool',
        ),
        migrations.AddField(
            model_name='route',
            name='pool_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_from', to='gql.pool'),
        ),
        migrations.AddField(
            model_name='route',
            name='pool_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_to', to='gql.pool'),
        ),
    ]
