# Generated by Django 4.2.11 on 2024-03-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gql', '0004_remove_route_pool_route_pool_from_route_pool_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetexchange',
            name='buying_asset',
        ),
        migrations.RemoveField(
            model_name='assetexchange',
            name='selling_asset',
        ),
        migrations.AddField(
            model_name='assetexchange',
            name='from_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_from', to='gql.asset'),
        ),
        migrations.AddField(
            model_name='assetexchange',
            name='to_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_to', to='gql.asset'),
        ),
    ]
